fix(proxmox-csi): remove pod security warning
use proper namespace security setting from terraform module and remove custom settings from kubernetes YAML

- use the terraform module which is the owner of the namespace
  - otherwise there was a field ownership warning when applyin the labels manually (cf. below)
  - namespace was privileged already (due to proper settings in helm chart), nervertheless also set enforce=privileged in addition to warn=privileged
- remove kustomize settings, this reverts 685609be70d00ba4ab557f245e0b039083f03c14

````
error: Apply failed with 1 conflict: conflict with "HashiCorp" using v1: .metadata.labels.pod-security.kubernetes.io/warn
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
```